version: "3"
services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exercism
    environment:
      - EXERCISM_API_KEY
    volumes:
      - ./files:/home/learn
    ports:
      - 8282:8000

    tty: true
    stdin_open: true